version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: schemasyncdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  schemasync:
    build: .
    depends_on:
      - postgres
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/schemasyncdb
      USER: user
      PASSWORD: pass
    volumes:
      - ./migrations:/app/migrations

volumes:
  pgdata:
